# Generated by Django 2.2.2 on 2019-06-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_date',
        ),
    ]
