# Generated by Django 2.2.2 on 2019-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0002_remove_user_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, to='sc.Group'),
        ),
    ]
